# Generated by Django 5.0.6 on 2024-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='grandTotal',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='option',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_list',
        ),
        migrations.RemoveField(
            model_name='optionlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartItems',
            field=models.ManyToManyField(to='api.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='addOns',
            field=models.ManyToManyField(blank=True, to='api.option'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionlist',
            name='Options',
            field=models.ManyToManyField(to='api.option'),
        ),
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='api.cartitem'),
        ),
        migrations.AddField(
            model_name='product',
            name='OptionsLists',
            field=models.ManyToManyField(blank=True, to='api.optionlist'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
