# Generated by Django 5.0.6 on 2024-06-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_options_optionlist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='optionsLists',
            new_name='optionslists',
        ),
    ]
