# Generated by Django 5.0.6 on 2024-06-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartItems',
            field=models.ManyToManyField(blank=True, to='api.cartitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='grandTotal',
            field=models.FloatField(default=0.0),
        ),
    ]
